### ISSUE TITLE
android 11点击播放按钮就闪退

### ISSUE THREAD

**Issue by dearliuliu0522** [luke358/podcasts_pro#1]
模拟器中的android12就正常，是否最低支持android12？报错如下：
![image](https://github.com/user-attachments/assets/3acc3886-6adc-4cf9-83aa-53307763fe98)

初学flutter，请问如何修改以指定android11及以上呢？

**Comment by dearliuliu0522** [comment]
在真机（android11）上具体复现是：
1、清空播放列表
2、回到首页“订阅”，随便点击一个播放，此时app闪退

最后问题找到了，修改代码如下：
![image](https://github.com/user-attachments/assets/1d913779-655e-4602-b1d7-e682ae834d45)

问题出在这。但在模拟器上没问题，修改后就可以在真机（android11）上跑了。

参考资料：https://stackoverflow.com/questions/74883579/fatal-exception-couldnt-inflate-contentviewsjava-lang-illegalargumentexceptio/74945227#74945227

**Comment by luke358** [comment]
fix by: e452560edbc1c03d853375afcd441a8131de2ec8
已经修复，可以拉取最新代码重新运行
